name: uts_mobile_programming_220040112
description: A new Flutter project

publish_to: 'none'

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  image_picker_web: ^2.0.3
  flutter_image_compress: ^0.7.0
  permission_handler: ^10.2.0




#flutter:
#  assets:
#    - assets/images/
